import Foundation

/// Stable destinations for the Help menu and contextual troubleshooting links.
public enum HelpTopicID: String, CaseIterable, Sendable {
    case gettingStarted, repositoryList, stagingAndCommit, history, branchesAndWorktrees
    case conflicts, syncAndUndo, stashes, reviews, reviewTroubleshooting
    case commandRunner, settings, keyboard, troubleshooting, refreshTroubleshooting
    case gitTroubleshooting, installation, safety
}

public enum HelpCategory: String, CaseIterable, Sendable {
    case start = "Getting Started"
    case git = "Working with Git"
    case reviews = "Code Reviews"
    case tools = "Tools and Preferences"
    case troubleshooting = "Troubleshooting"
}

public struct HelpSection: Sendable {
    public let title: String
    public let paragraphs: [String]
    public let steps: [String]

    init(_ title: String, _ paragraphs: [String] = [], steps: [String] = []) {
        self.title = title
        self.paragraphs = paragraphs
        self.steps = steps
    }
}

public struct HelpArticle: Identifiable, Sendable {
    public let id: HelpTopicID
    public let category: HelpCategory
    public let title: String
    public let summary: String
    public let symbol: String
    public let keywords: [String]
    public let sections: [HelpSection]
    public let related: [HelpTopicID]
}

/// Compiled into the app so Help remains available offline and in copied builds.
public enum HelpContent {
    public static func article(_ id: HelpTopicID) -> HelpArticle? {
        articles.first { $0.id == id }
    }

    /// Every query term must match. Titles and aliases rank above body matches;
    /// ties keep the curated article order. Punctuation and accents are ignored.
    public static func search(_ query: String) -> [HelpArticle] {
        let terms = normalized(query).split(separator: " ").map(String.init)
        guard !terms.isEmpty else { return articles }
        return articles.enumerated().compactMap { index, article -> (Int, Int, HelpArticle)? in
            let title = normalized(article.title)
            let aliases = normalized(article.keywords.joined(separator: " "))
            let summary = normalized(article.summary)
            let body = normalized(article.sections.flatMap { [$0.title] + $0.paragraphs + $0.steps }.joined(separator: " "))
            let fields = [title, aliases, summary, body]
            guard terms.allSatisfy({ term in fields.contains { $0.contains(term) } }) else { return nil }
            let score = terms.reduce(0) { score, term in
                score + (title.contains(term) ? 12 : aliases.contains(term) ? 8 : summary.contains(term) ? 4 : 1)
            } + (title == terms.joined(separator: " ") ? 30 : 0)
            return (score, index, article)
        }.sorted { lhs, rhs in
            lhs.0 == rhs.0 ? lhs.1 < rhs.1 : lhs.0 > rhs.0
        }.map { $0.2 }
    }

    private static func normalized(_ text: String) -> String {
        text.folding(options: [.caseInsensitive, .diacriticInsensitive], locale: Locale(identifier: "en_US_POSIX"))
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber }).joined(separator: " ")
    }

    public static let articles: [HelpArticle] = [
        HelpArticle(id: .gettingStarted, category: .start, title: "Get started with RepoDeck",
            summary: "Add existing repositories and choose a workspace.", symbol: "house", keywords: ["welcome", "add folder", "first launch", "clone"], sections: [
                HelpSection("Your first repository", ["RepoDeck works with existing local Git repositories. Clone or initialize a repository using Git or another tool first; adding a folder does not create a repository or upload anything."], steps: [
                    "Choose Add Folder… in the main window and select a repository or a parent folder containing several repositories.",
                    "Select a repository in the sidebar. Its branch, changed-file count, and ahead/behind indicators show what needs attention.",
                    "Use the Workspace selector to open Changes, History, Branches & Worktrees, Conflicts, or Reviews. In a narrow window the selector is a compact menu."
                ]),
                HelpSection("A typical change", steps: ["Open Changes and inspect a file with View Diff.", "Stage the intended files or eligible hunks. Enter a commit message and choose Commit.", "Use Fetch to check remote changes, then Pull or Push when appropriate. Review any error before retrying."]),
                HelpSection("This help works offline", ["Search the titles and full text of these topics. Related Topics links connect common next steps. Help does not run Git commands or submit reviews. Repository and hosting work continues in the main window."])
            ], related: [.repositoryList, .stagingAndCommit, .keyboard, .troubleshooting]),
        HelpArticle(id: .repositoryList, category: .start, title: "Find and organize repositories",
            summary: "Folders, worktree discovery, filters, pinning, groups, and hidden repositories.", symbol: "folder", keywords: ["sidebar", "missing repo", "remove from list", "restore", "hidden", "bare", "scan"], sections: [
                HelpSection("What appears in the sidebar", ["RepoDeck scans added folders up to eight levels deep and skips common dependency/build directories during discovery. It also asks Git for registered worktrees, including linked checkouts outside the selected folder. A bare repository can lead to its worktrees; it is not itself an editable checkout.", "Use Refresh Repositories (⌘R) after moving or adding repositories. To include a repository inside a skipped folder, add that repository directly."]),
                HelpSection("Filter and organize", ["Filter repositories searches repository names and branches. The Show menu can limit the sidebar to uncommitted changes, conflicts, repositories needing push or pull, or errors.", "Right-click a repository to Pin or Unpin it, choose Move to Group, or open Repository Settings… to create a group. Pinned repositories stay in the Pinned section."]),
                HelpSection("Hide or stop tracking", ["Remove from List hides the selected repository without deleting its files. Restore it from Folders → Hidden Repositories, or choose Show All there.", "Folders → a tracked folder → Remove stops tracking that folder. It does not remove anything from disk. A checkout may still be found through another tracked folder or registered worktree."])
            ], related: [.gettingStarted, .branchesAndWorktrees, .refreshTroubleshooting]),
        HelpArticle(id: .stagingAndCommit, category: .git, title: "Stage changes and commit",
            summary: "Inspect changes, stage whole files or text hunks, and save a commit.", symbol: "checkmark.circle", keywords: ["index", "unstage", "patch", "diff", "commit message", "partial staging", "hunk"], sections: [
                HelpSection("Choose what goes into the commit", steps: ["Select Changes. A file with both staged and unstaged edits appears in both sections.", "Choose View Diff to inspect the selected version of a changed file. Stage or Unstage a file using its row control; Stage All stages the displayed repository's changes.", "In a working-file diff, use Stage Hunk or Unstage Hunk for eligible text hunks. Commit diffs are read-only.", "Enter a commit message and choose Commit, or press ⌘Return while the message field has focus. Only staged content is committed."]),
                HelpSection("When a whole-file action is required", ["Hunk actions require lossless UTF-8 text and supported, unchanged file metadata. Binary content, other encodings, symlinks, submodules, renames, and mode changes may need whole-file staging. Read the explanation in the diff before choosing that alternative.", "The app checks that the displayed diff still matches the repository before applying a hunk. If the file changed elsewhere, refresh and inspect the new diff before trying again. Never assume an old hunk still represents your intended change."]),
                HelpSection("If committing fails", ["Read the reported Git or hook error. Check that the commit has a message, staged changes, and a valid commit author. Use Configure Commit Author to set your default name and email and check which author Git will use. RepoDeck uses your installed Git and hooks. A failed commit preserves the message; an edit made while a commit is running is not cleared by that earlier submission.", "Unmerged files must be resolved first. A partial status list is incomplete; use Git in a terminal to inspect the full repository before a broad action."])
            ], related: [.conflicts, .gitTroubleshooting, .safety]),
        HelpArticle(id: .history, category: .git, title: "Explore history and the commit graph",
            summary: "Browse commits, inspect parent relationships, and search history.", symbol: "point.3.connected.trianglepath.dotted", keywords: ["log", "search commits", "author", "pickaxe", "file path", "pagination", "tags"], sections: [
                HelpSection("Browse the graph", ["Choose History to see parent connections and branch/tag decorations. The graph offers current history or All branches and tags, with 100-commit pages. Load 100 More Commits reveals older history. Select a commit to inspect it, navigate to a parent, or open its diff."]),
                HelpSection("Search", ["Choose a search scope: Message, Author, File, or Content. Content uses Git's pickaxe search to find commits that change occurrences of the requested text. Search is limited to up to 100 matches from the current HEAD's history; the graph's All branches and tags switch does not expand the search scope.", "A new repository with no commits has no history yet. Detached HEAD means the checkout is at a commit rather than an active local branch."])
            ], related: [.branchesAndWorktrees, .stagingAndCommit, .refreshTroubleshooting]),
        HelpArticle(id: .branchesAndWorktrees, category: .git, title: "Manage branches and worktrees",
            summary: "Switch branches, set tracking, and work in multiple checkouts.", symbol: "arrow.triangle.branch", keywords: ["upstream", "tracking", "checkout", "rename branch", "delete branch", "work tree", "merge", "rebase"], sections: [
                HelpSection("Branches", ["Choose Branches & Worktrees. Enter a New branch name and optional Starting revision, then Create & Switch. A remote branch's Actions → Create Tracking Branch… fills those fields; finish with Create & Switch.", "Use a local branch's Actions menu to Switch, Rename, Delete Merged Branch, Set Tracking, or Remove Tracking. Enter the new name or upstream in the corresponding field first. Read the confirmation's repository and branch before applying a change. Deletion is limited to safely merged branches; Git may refuse a branch checked out in another worktree.", "Merge into Current Branch and Rebase Current Branch onto This require a clean working tree. Commit or stash your work first. Rebase rewrites local history: inspect the selected branch and base carefully, especially if those commits are shared."]),
                HelpSection("Separate worktrees", ["A worktree is a separate working directory sharing Git history and some metadata with the repository. Choose a new directory and branch in Branches & Worktrees, then Use Existing Branch or Create New Branch. Open selects that checkout. Registered linked worktrees can appear in the sidebar even outside your originally tracked folder.", "Remove… refuses the current/main/locked worktree and worktrees with tracked changes or untracked files, including ignored files such as local .env files. Back up or deliberately relocate those files yourself; a clean-looking normal Git status does not prove the directory is disposable."]),
                HelpSection("When an action is refused", ["A confirmation is tied to the branch and repository state you reviewed. If that state changed while waiting, refresh and start the action again. If Git reports an operation in progress, use Conflicts or finish the operation in a terminal before starting a different operation."])
            ], related: [.conflicts, .syncAndUndo, .stashes, .safety]),
        HelpArticle(id: .conflicts, category: .git, title: "Resolve conflicts",
            summary: "Edit a text resolution, stage it explicitly, and continue or abort Git operations.", symbol: "arrow.triangle.merge", keywords: ["unmerged", "merge conflict", "rebase conflict", "ours", "theirs", "base current incoming", "mark resolved", "abort"], sections: [
                HelpSection("Resolve a supported text file", steps: ["Open Conflicts and select an unmerged file. Read Base, Current, and Incoming, then edit the Result.", "Choose Save Result to write the result to the working file. Saving alone does not mark the conflict resolved.", "Review the saved result, then choose Mark Resolved to stage it. Repeat for the remaining conflicts.", "Use Continue when the current Git operation is ready. Read any Git message if further work is required."]),
                HelpSection("Current and incoming during a rebase", ["Git's ours/theirs roles can be surprising during rebase: the current side is the branch being rebased onto, while incoming represents the commit being replayed. Read the operation-aware labels rather than assuming the side names always mean your original branch versus someone else's."]),
                HelpSection("External tools and unsupported conflicts", ["Use Open in Configured Editor or Open Terminal for binary files, unsupported encodings, symlinks, submodules, or complex conflicts. After resolving externally, reload and use Mark Resolved (Stage Whole File)…. Confirm only after inspecting the current file, including any intended deletion.", "If a file or its index stages changed after loading, RepoDeck refuses a stale save or resolution. Your draft is retained, but Reload from Disk… explicitly replaces it. Preserve your intended text before reloading, inspect the new conflict, and apply the resolution again."]),
                HelpSection("Continue or Abort", ["These actions apply to the detected merge, rebase, cherry-pick, or revert. Abort asks Git to abandon that operation; inspect its preview before confirming. Worktree changes or a retained autostash may still need attention. Interactive rebase editing belongs in an external terminal."])
            ], related: [.branchesAndWorktrees, .stagingAndCommit, .gitTroubleshooting, .safety]),
        HelpArticle(id: .syncAndUndo, category: .git, title: "Fetch, pull, push, and undo",
            summary: "Synchronize safely and understand the scope of sync undo.", symbol: "arrow.triangle.2.circlepath", keywords: ["remote", "ahead", "behind", "non fast forward", "rejected push", "autostash", "auto fetch", "reset keep"], sections: [
                HelpSection("Choose the operation", ["Fetch downloads remote history without merging it into your working branch. Pull integrates changes according to Git and repository configuration. Push sends local commits to the configured remote/upstream. Ahead and behind counts compare the current branch with its upstream; fetch first when those counts may be out of date.", "Fetch All and Pull All operate across tracked repositories. Their summary distinguishes succeeded, failed, and skipped repositories. Busy repositories can be skipped; inspect the result rather than assuming every repository completed."]),
                HelpSection("Automatic options", ["Repository Settings… offers Auto-Fetch intervals of 5, 15, 30, or 60 minutes, or Off. Auto-fetch uses a capped background queue; interactive requests have priority over queued background work.", "Auto-Rebase on Rejected Push is off by default. When enabled per repository, a non-fast-forward push rejection can trigger pull --rebase --autostash and one push retry. If rebase conflicts, the app attempts to abort; inspect Conflicts and any retained stash before proceeding."]),
                HelpSection("What Undo restores", ["Before a pull or auto-rebase push, RepoDeck can record the starting commit in a Git ref. Undo is one level for that worktree and branch, uses reset --keep, and refuses when the recorded state no longer matches or local edits would be overwritten.", "Undo does not undo a remote push or back up arbitrary untracked/ignored files. It is not general undo for every Git operation. Back up local work before recovery if you are unsure."])
            ], related: [.gitTroubleshooting, .conflicts, .stashes, .safety]),
        HelpArticle(id: .stashes, category: .git, title: "Save and restore stashes",
            summary: "Set work aside and understand Apply, Pop, and Drop.", symbol: "archivebox", keywords: ["stash apply", "stash pop", "stash drop", "untracked", "ignored"], sections: [
                HelpSection("Create a stash", ["Choose Stash to set aside the current repository's tracked changes and untracked files. Ignored files are not included. A stash is local to Git; it is not a remote backup."]),
                HelpSection("Use an existing stash", ["The Stashes section lists each entry. Right-click an entry and choose Apply to restore its changes while keeping the stash, Pop to restore and remove it if successful, or Drop to remove the entry without applying it. Drop requires confirmation.", "Restoring can conflict with current files. Inspect Conflicts and Git's result before repeating an action. Refresh if the selected stash changed elsewhere; the app binds selections to the stash object rather than trusting an old row number."])
            ], related: [.conflicts, .syncAndUndo, .safety]),
        HelpArticle(id: .reviews, category: .reviews, title: "Review GitHub pull requests and GitLab merge requests",
            summary: "Connect a host, inspect a review, and preview any submission.", symbol: "text.bubble", keywords: ["PR", "MR", "pull request", "merge request", "approve", "request changes", "create draft", "checks", "fork"], sections: [
                HelpSection("Connect and read", steps: ["Install and sign in to gh for GitHub or glab for GitLab using your terminal. Local Git work does not require either tool.", "Choose Reviews, select the intended Remote and Provider, then Connect / Refresh. Check the displayed host, account, and repository.", "Select a request and inspect Overview, Files, Checks, or Discussion. Load More fetches another page. Use Open in Browser when a file patch or provider feature is unavailable."]),
                HelpSection("Create or submit", ["New creates a request from an already-pushed source branch. Select Source remote, enter the source and destination branches, title, and description, and choose whether to Create as draft. Preview Creation… shows the destination before submission. Mark Ready… converts a draft when supported.", "For an existing review, enter a Review message, choose an action, and use Preview Submission…. GitHub offers Comment, Approve, and Request Changes. GitLab supports comments and approvals; its approval action submits the approval only. Use a comment or browser workflow for formal changes on GitLab.", "Merge… previews the chosen method and expected head. Server permissions, protection rules, draft state, and project configuration determine whether merging is allowed. RepoDeck does not bypass those rules."]),
                HelpSection("Check out without replacing your current files", ["Open in New Worktree… fetches the reviewed commit into a new detached worktree. Choose a new directory and review the preview. The fetched commit must match the reviewed head. This does not replace your current checkout."]),
                HelpSection("Drafts and supported scope", ["Review selection and unsent text are saved locally by worktree and destination. After an uncertain create/comment result, reconnect and let the app check for the existing submission before retrying the same action. Do not create a duplicate manually until you have checked the server.", "Comments are general review submissions; inline threaded-comment editing is not available. GitHub shows head and relevant test-merge checks; GitLab shows its latest pipeline summary. No checks reported is not the same as passing checks."])
            ], related: [.reviewTroubleshooting, .branchesAndWorktrees, .settings, .safety]),
        HelpArticle(id: .reviewTroubleshooting, category: .reviews, title: "Fix hosting connections and review errors",
            summary: "Missing tools, expired credentials, permissions, stale heads, and uncertain submissions.", symbol: "network", keywords: ["gh", "glab", "401", "403", "authentication", "expired credentials", "token", "permission denied", "protected branch", "GitHub", "GitLab", "offline"], sections: [
                HelpSection("Tool missing or authentication expired", steps: ["Check Settings → Developer Tools. Choose the installed gh or glab executable if automatic PATH discovery cannot find it, then Apply Workflow Settings.", "In an external terminal, use that CLI's authentication workflow for the displayed host and intended account. Enterprise or self-hosted services need the correct hostname. RepoDeck does not ask you to paste access tokens into Help or import CLI credentials.", "Return to Reviews, verify the Remote and Provider, then Connect / Refresh. A failure on one host does not establish the state of another account or host."]),
                HelpSection("Sign in to the expected GitHub host", ["For github.com, run the following in an external terminal. For GitHub Enterprise, replace github.com in both commands with the exact hostname shown in Reviews. Follow the CLI's prompts and select the account that should access this repository.", "gh auth login --hostname github.com\ngh auth status --hostname github.com", "Check the reported active account, then return to Reviews and choose Connect / Refresh. If Settings points to a custom gh executable, use that same executable in the terminal rather than a different copy on PATH."]),
                HelpSection("Sign in to the expected GitLab host", ["For gitlab.com, run the following in an external terminal. For a self-managed service, replace gitlab.com in both commands with the hostname shown in Reviews. Complete the CLI's sign-in prompts for the intended account.", "glab auth login --hostname gitlab.com\nglab auth status --hostname gitlab.com", "Verify the host/account reported by the CLI, then return to Reviews and choose Connect / Refresh. Use the same glab executable selected in Settings. Do not include tokens in copied diagnostic output or a bug report."]),
                HelpSection("Permission or protection rejection", ["A 401/403 response, required approval, failed check, or protected-branch rule needs attention on the hosting service. Read the error and use Open in Browser to inspect your permission or the required condition. Repeating the same merge or review cannot grant access or bypass protection."]),
                HelpSection("The head, account, or destination changed", ["Refresh and inspect the latest request before making a new preview. Do not confirm a submission for a different account, repository, or commit than the one you intended to review. Drafts remain associated with their destination."]),
                HelpSection("Offline or uncertain outcome", ["When a request times out, the server may still have accepted it. Check the request in a browser when connectivity returns. Keep the draft and retry through the same pending action so RepoDeck can reconcile supported creation/comment submissions first. A reconciliation error needs resolution before a safe retry.", "Missing or oversized file patches and failed check loads are shown explicitly. Use the provider's browser UI for complete files, unsupported actions, and administration."])
            ], related: [.reviews, .settings, .troubleshooting]),
        HelpArticle(id: .commandRunner, category: .tools, title: "Use the command runner or a terminal",
            summary: "Run bounded shell commands and stop them explicitly.", symbol: "terminal", keywords: ["shell", "run command", "stop", "cancel", "stdout", "stderr", "TTY", "vim", "history", "output limit"], sections: [
                HelpSection("Run a command", ["Right-click a repository and choose Open Command Runner, or use the Command Runner button in the sync controls. Commands run in that repository using your login shell. Type the command and press Return or Run; use the up/down arrows in the command field to recall history.", "The pane keeps a bounded output history per repository. ANSI styling is removed from the displayed text. Commands can modify files and Git state just as they would in a shell; inspect what you are about to run."]),
                HelpSection("Stop and cleanup", ["Choose Stop to cancel the running command and its owned process group. Closing the pane hides it; it does not mean the command was stopped. The app keeps its repository coordination until cleanup finishes.", "The runner limits output and stops a command that exceeds the budget. Its child processes belong to that command and are cleaned up when it ends. Use a real terminal for long-running background services."]),
                HelpSection("When you need a terminal", ["The pane has no interactive TTY and its standard input is closed. Use Open in Terminal for editors such as vim, password prompts, interactive rebase, terminal applications, and other interactive commands. Choose your terminal application in Settings or Repository Settings…."])
            ], related: [.settings, .gitTroubleshooting, .safety]),
        HelpArticle(id: .settings, category: .tools, title: "Configure tools, applications, and appearance",
            summary: "Set executable paths, editor/terminal choices, fonts, themes, and repository overrides.", symbol: "gearshape", keywords: ["preferences", "PATH", "TextEdit", "terminal app", "fonts", "dark mode", "light mode", "menu bar", "apply workflow settings"], sections: [
                HelpSection("Global settings", ["Choose RepoDeck → Settings… (⌘,). Appearance, accent color, fonts, font size, and Show menu bar icon are configured here. Reset to Defaults resets the appearance settings.", "Developer Tools accepts executable file paths for Git, gh, and glab. Paths must be absolute and executable. Git is required; a blank gh or glab path uses automatic discovery. Changing tools or applications takes effect when you choose Apply Workflow Settings."]),
                HelpSection("Editors and terminals", ["Use Choose… to select an installed .app for Editor or Terminal. With no editor selected, files open using their macOS default application. Open in Editor/Open in Terminal actions use the selected repository's override, if any, then the global preference.", "Right-click a repository → Repository Settings… to override its editor or terminal, set Auto-Fetch, toggle Auto-Rebase on Rejected Push, or assign a group. Repository settings apply immediately; Use Global removes an application override."]),
                HelpSection("If a selected tool no longer exists", ["Choose its new installed location and apply the workflow settings again. Do not enter a command with flags into an executable-path field. Authentication is handled by Git/hosting tools, not by selecting the application path."])
            ], related: [.keyboard, .reviewTroubleshooting, .commandRunner]),
        HelpArticle(id: .keyboard, category: .tools, title: "Keyboard shortcuts and navigation",
            summary: "Find actions, navigate lists, resize panes, and search Help.", symbol: "keyboard", keywords: ["accessibility", "VoiceOver", "keyboard shortcuts", "command k", "cmd k", "command question", "help shortcut"], sections: [
                HelpSection("App shortcuts", ["⌘? opens the macOS Help menu/search. Choose RepoDeck Help there to open this guide. In the Help window, ⌘F focuses Search Help, ⌘[ goes back, and ⌘] goes forward.", "⌘K opens Command Palette to find repositories or common actions. Use its arrow keys and Return to choose a result; Escape dismisses it.", "⌘R refreshes tracked repositories. ⌘, opens Settings…. ⌘Return commits while the commit-message field has focus."]),
                HelpSection("Within a workspace", ["Use the native list selection and arrow keys to move through repositories or Help topics. The command input uses Return to run and up/down to recall commands. Its Stop button cancels a command.", "Resizable pane dividers expose keyboard/VoiceOver adjustment alongside dragging. Use macOS Keyboard Navigation or Full Keyboard Access if you want keyboard focus to reach all controls. Increasing font size in Settings can improve readability."]),
                HelpSection("Context menus", ["Right-click or Control-click a repository, file, commit, or stash to reveal the actions available for that item. Disabled actions often mean the repository is busy, an operation is in progress, or the selected content requires a different workflow."])
            ], related: [.gettingStarted, .settings, .commandRunner]),
        HelpArticle(id: .troubleshooting, category: .troubleshooting, title: "Troubleshooting: start here",
            summary: "Read the error, preserve work, and choose the right recovery path.", symbol: "lifepreserver", keywords: ["error", "failed", "problem", "warning", "broken", "recovery", "dismiss", "diagnostic"], sections: [
                HelpSection("Before retrying", steps: ["Choose Details & Help… on an error to read the explanation, next steps, and full technical details. Note which repository and action it belongs to. Dismissing a message does not fix its cause.", "Preserve unsent text or local files you need. Avoid repeating a write until you know whether the previous attempt completed.", "Use an appropriate next step such as Show Changes, Show Conflicts, Show Branches, Open Settings, Open Terminal, or Refresh Status. These help you inspect or navigate; they do not automatically repeat a failed write.", "Choose the related topic below for repository refresh, Git/sync errors, hosting connections, or conflict resolution. A stale preview needs a new review and confirmation."]),
                HelpSection("Full details without losing your workspace", ["Inline messages show a short summary. Details & Help… opens the full error in a scrollable sheet; Copy Details copies its technical text for inspection or a bug report. Informational notices have Details… for the complete message.", "Fetch All and Pull All summaries have Results… with each repository's Succeeded, Failed, or Skipped outcome. Expand Details and next steps for an explanation, or Open Repository to inspect it. A summary dismissal does not retry any action."]),
                HelpSection("Busy or skipped is different from failed", ["A repository can be waiting for another operation sharing its Git metadata. Let the active operation finish, or Stop a command you intentionally want to cancel. Inspect the reason for a skipped bulk action: a busy repository was not started, while a cancelled action may already have made changes. Check its current state before trying again."]),
                HelpSection("What to include in a bug report", ["Record the RepoDeck version, macOS version, workspace/action, exact error, and whether it happens in a linked worktree or only with one host. Include the smallest reproducible example you can share. Remove tokens, credentials, private source, and personal paths from any copied diagnostic text.", "Help is available offline. Sharing an issue or contacting a hosting service requires a separate action; this window does not upload diagnostics."])
            ], related: [.refreshTroubleshooting, .gitTroubleshooting, .reviewTroubleshooting, .conflicts, .safety]),
        HelpArticle(id: .refreshTroubleshooting, category: .troubleshooting, title: "Repository missing or status out of date",
            summary: "Check discovery, hidden items, worktrees, and incomplete status.", symbol: "arrow.clockwise", keywords: ["refresh", "rescan", "watcher", "vendor", "target", "folder permissions", "too many changes", "partial list", "didHitLimit"], sections: [
                HelpSection("A repository is missing", steps: ["Clear Filter repositories and set Show to All repositories.", "Check Folders → Hidden Repositories and restore the entry if it was hidden.", "Confirm that its directory still exists and that a parent folder is tracked. Add the checkout directly if it is deeply nested or inside a dependency/build directory skipped during discovery.", "Press ⌘R. If discovery reports an error, check folder permissions and the Git executable in Settings. A bare repository itself is not shown as an editable worktree."]),
                HelpSection("The display looks stale", ["Press ⌘R after moving checkouts or changing Git metadata externally. RepoDeck watches working files and linked-worktree metadata, but a refresh error must be resolved before you can rely on the displayed snapshot.", "If an open diff or operation preview no longer matches, reopen it after refresh. Do not apply an old preview to a different branch or worktree."]),
                HelpSection("Too many changes — partial list", ["Status output is bounded. A partial-list warning means some changes are not shown; it does not mean those files are clean. Inspect the full repository with Git in a terminal, and use appropriate ignore rules for generated files when that matches your project's intent.", "Large or unsupported diffs may be refused rather than shown as complete. Use an external diff tool or whole-file workflow after reviewing the actual content."])
            ], related: [.repositoryList, .settings, .gitTroubleshooting]),
        HelpArticle(id: .gitTroubleshooting, category: .troubleshooting, title: "Fix Git, sync, and commit errors",
            summary: "Commit authors, hooks, locks, upstreams, network failures, and rejected writes.", symbol: "wrench.and.screwdriver", keywords: ["git error", "commit failed", "push rejected", "pull failed", "fetch failed", "index lock", "permission denied", "authentication", "timeout", "identity", "commit author", "user name", "user email", "author name", "author email"], sections: [
                HelpSection("Git cannot run or commit", ["Check the Git executable in Settings → Developer Tools, then Apply Workflow Settings. RepoDeck uses the installed Git configuration, including commit author settings, credential helpers, SSH setup, and hooks.", "A hook failure needs the hook's reported issue fixed. Hooks and credential helpers that need interactive input may require an external terminal."]),
                HelpSection("Configure your commit author in RepoDeck", ["Select a repository and choose Configure Author under Commit author in the sidebar footer. When Git resolves a complete author, the action is Edit Author. The same setup is available in Repository Settings and from commit-author errors. Unavailable under Commit author means Git could not resolve the current author; Retry reads it again, and Configure Author opens the settings and full diagnostic.", "Enter your default name and email. The form edits Git’s user.name and user.email settings. Choose This repository to save them for that repository, including linked worktrees sharing its configuration, or My Git default to set the defaults used by Git on this Mac and other Git apps. Repository, worktree, author.name/author.email, or environment settings can override those defaults.", "Review the displayed destination and choose Save Commit Author. Author for new commits shows the author Git resolves for ordinary new commits, which may differ from the defaults you saved. Opening the form does not change settings. A failed save preserves your entries; because Git writes the name and email separately, an interrupted save may have saved one field. Read the error and reload the settings before saving again.", "If the defaults can be read but the author is unavailable, you can still save the defaults to repair them. The warning retains Git’s diagnostic and offers Reload Author. If an author-specific or environment override remains invalid, correct that override at its source and reload. A successfully saved default does not guarantee that every overriding setting is valid.", "SSH keys authenticate access to a remote, and your GitHub or GitLab account identifies the hosting account. They do not automatically supply the author stored inside commits. The sidebar’s GitHub account row is separate from Commit author. Review the displayed author, staged changes, and commit message before choosing Commit. Existing commits retain their authors, and cherry-pick and rebase normally preserve the original commit’s author."]),
                HelpSection("Set your default name and email for this repository", ["As a terminal alternative, select the repository and choose Open in Terminal. Run these commands from its directory, replacing Your Name and you@example.com with the default name and email you want recorded in new commits. Keep the quotation marks around your values.", "git config --local user.name \"Your Name\"\ngit config --local user.email \"you@example.com\"", "These defaults apply to this repository, including linked worktrees that share its configuration. They leave your global defaults unchanged. Ask Git which author it resolves before committing:", "git var GIT_AUTHOR_IDENT", "The output includes the author’s name, email, timestamp, and time zone. Reading user.name and user.email alone does not account for author-specific or environment overrides. Inspect their origins with git config --show-origin --get user.name, git config --show-origin --get user.email, git config --show-origin --get author.name, and git config --show-origin --get author.email. GIT_AUTHOR_NAME and GIT_AUTHOR_EMAIL can also take precedence. Use the Git executable configured in RepoDeck; your terminal environment may differ from the app’s.", "Return to RepoDeck, refresh, and review its displayed commit author, staged changes, and commit message. Choose Commit again only when these are correct. These commands do not rewrite existing commits."]),
                HelpSection("Push rejected or no upstream", ["Fetch and inspect incoming commits first. Set the intended tracking branch in Branches & Worktrees if no upstream exists. Integrate changes through a reviewed pull, merge, or rebase workflow before pushing again. Do not use force push as a generic fix for someone else's newer commits.", "Auto-Rebase on Rejected Push is optional and may require conflict or autostash recovery. Read the error and inspect Conflicts and Stashes rather than repeating it blindly."]),
                HelpSection("Lock or operation already in progress", ["Another Git process may own an index lock or be performing a merge/rebase. Wait for it to finish and inspect the repository in a terminal. Do not delete a lock file while a Git process may still be using it. Use the existing operation's Continue/Abort workflow instead of starting a competing one."]),
                HelpSection("Network, authentication, or timeout", ["Check connectivity, the remote URL, and the credentials/SSH configuration used by your Git executable. Use an external terminal if the tool needs a prompt. Git's own remote authentication is separate from the gh/glab Reviews connection.", "A timeout does not by itself prove the remote made no change. Fetch and inspect remote state before retrying a push. Preserve any local error details and unsent message while you determine what completed."])
            ], related: [.syncAndUndo, .conflicts, .settings, .reviewTroubleshooting]),
        HelpArticle(id: .installation, category: .start, title: "Install, update, and open RepoDeck",
            summary: "macOS requirements, the disk image, and first-launch approval.", symbol: "square.and.arrow.down", keywords: ["install", "download", "update", "Gatekeeper", "unnotarized", "ad hoc", "Apple silicon", "Intel", "macOS", "Open Anyway"], sections: [
                HelpSection("Install or update", ["RepoDeck requires macOS 15 or later. The release installer includes Apple silicon and Intel support. Download the installer and its SHA-256 checksum from the project's GitHub release page, verify the download, open the disk image, and drag RepoDeck to Applications.", "To update, quit the running app before replacing it with the newer copy. Releases are available at github.com/sergio-farfan/repodeck/releases. RepoDeck does not provide an automatic in-app updater."]),
                HelpSection("First launch", ["The standard release is ad-hoc signed and not notarized. After verifying a trusted download and attempting to open it, you may need System Settings → Privacy & Security → Open Anyway. Device-management policy can restrict this option. Follow Apple's app-specific instructions; do not disable system-wide security to open an app.", "Developer ID signing and notarization are optional future distribution choices, not requirements for using this standard release."]),
                HelpSection("Build from source", ["The project uses Swift Package Manager and Swift 6.2 or newer. The documented development commands are swift build, swift test, and swift run RepoDeck. See the repository's README for packaging instructions. Local Git work requires Git; gh and glab are optional for hosting integration."])
            ], related: [.gettingStarted, .settings, .troubleshooting]),
        HelpArticle(id: .safety, category: .troubleshooting, title: "Understand safety limits and recovery",
            summary: "What previews, drafts, undo, and coordination can protect.", symbol: "shield", keywords: ["data loss", "backup", "stale", "external git", "recover", "reset", "force", "limitations"], sections: [
                HelpSection("Preview the current state", ["Repository actions are checked against the worktree, branch, commit, and operation state you reviewed. If any of those change, refresh and create a new preview. Other Git programs do not share RepoDeck's coordinator and can still race an individual Git command."]),
                HelpSection("Keep recoverable work", ["Commit or back up important local work before a significant history change. A stash does not include ignored files by default. Sync Undo is limited to its recorded branch/worktree/commit, does not undo a remote push, and is not a general backup.", "Save and Mark Resolved are distinct. Read a whole-file staging or Abort confirmation carefully. Safe worktree deletion refuses local files that would otherwise be lost."]),
                HelpSection("Errors and unsent text", ["Commit and review drafts are preserved on errors; successful submissions clear only the text that was actually submitted. Before reloading a conflict document after an external change, copy any intended result you need to keep.", "For uncertain remote creation/comments, preserve the pending action and let the app reconcile it when the service is available. If you need manual recovery, inspect Git and the hosting service first rather than assuming the first attempt did nothing."]),
                HelpSection("Use the appropriate tool", ["Use an external terminal/editor for unsupported encodings, complex conflicts, interactive rebase, terminal prompts, and advanced Git operations. Use a hosting service's browser UI for inline threaded reviews and unsupported provider features. RepoDeck's previews do not replace reviewing the actual content you are about to commit, stage, or publish."])
            ], related: [.conflicts, .syncAndUndo, .stashes, .troubleshooting])
    ]
}
